# Generated by Django 4.1.5 on 2023-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(max_length=100)),
                ('Name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Finished', 'Finished')], default='In Progress', max_length=32)),
            ],
        ),
    ]
