# Generated by Django 4.1.5 on 2023-11-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Number',
        ),
    ]
